services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ativotrack
      POSTGRES_PASSWORD: ativotrack
      POSTGRES_DB: ativotrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    environment:
      POSTGRES_USER: ativotrack
      POSTGRES_PASSWORD: ativotrack
      POSTGRES_DB: ativotrack_test
    ports:
      - "5433:5432"

volumes:
  postgres_data: